package javaproject;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.sql.SQLException;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.filechooser.FileFilter;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class ManageStudent extends javax.swing.JInternalFrame {
    File myfile;
   String oldname;
    String default_img_name="second.jpg";
     
    public ManageStudent() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTextField4 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        jLabel4.setBackground(new java.awt.Color(204, 255, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("                                                                                  Manage Student");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Fetch");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Male");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Female");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("Gender");

        jDateChooser1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jDateChooser1KeyTyped(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("Name");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("User Name");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("Password");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("DOB");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Address");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setText("Phone");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("Branch and Sem");

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Branch", "Btech", "Mtech", "Bsc", "Commerce" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setText("Course");

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Semester", " " }));

        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 3));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setText("Upload photo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Phone", "Gender", "DOB", "Address", "Username"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 153));
        jButton6.setText("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 958, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2))
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField4)
                                    .addComponent(jPasswordField1)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(check_validation()==false)
        return;
        //save image
     
        String filename="";
        if(myfile==null)
        {
            filename=default_img_name;
        }
        else
        {
            if(myfile.length()>900000000){
                JOptionPane.showMessageDialog(rootPane,"Image is tooo large");
                return;
            }
            else{
                filename=new java.util.Date().getTime()+myfile.getName();
                int i;
                FileInputStream rd=null;
                FileOutputStream outs=null;
                try{
                    rd=new FileInputStream(myfile);
                    outs=new FileOutputStream("user_image//"+filename);//C:\\Users\\hp\\JavaProject\\user_image
                    byte[]b=new byte[2048];
                    while((i=rd.read())!=-1)
                    {
                        outs.write(b, 0, i);
                    }
                }
                catch(Exception e){
                JOptionPane.showMessageDialog(rootPane,"Error : "+e.getMessage());
            }
                finally
                {
                    try
                    {
                        rd.close();
                        outs.close();
                    }
                    catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(rootPane,"Error in closing file "+e.getMessage());
                    }
                }
            }
        }

    //SAVE
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=null;
            conn=DriverManager.getConnection("jdbc:mysql://localhost/javaproject","root","");
            try{
                String qry="insert into managestudent values(?,?,?,?,?,?,?,?,?,?,?)";
                PreparedStatement st=conn.prepareStatement(qry);
                st.setString(1,jTextField1.getText());
                st.setString(2,jTextField2.getText());
                if(jRadioButton1.isSelected())
                st.setString(3,"male");
                else
                st.setString(3,"female");
                SimpleDateFormat myformat = new SimpleDateFormat("yyyy-MM-dd");
                String d1 = myformat.format( jDateChooser1.getDate() );
                st.setString(4, d1);
                st.setString(5,jTextArea1.getText());
                st.setString(6,jTextField4.getText());
                st.setString(7,jPasswordField1.getText());
                st.setString(8,jComboBox1.getSelectedItem().toString());
                st.setString(9,jComboBox3.getSelectedItem().toString());
                st.setString(10,jComboBox2.getSelectedItem().toString());
                st.setString(11,filename);
                int rowcount=st.executeUpdate();
                if(rowcount==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"User added Sucessfully");
                    clearpage();
                }
                else
                JOptionPane.showMessageDialog(rootPane,"Check all fields");
                
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(rootPane,"Query Error : "+ex.getMessage());
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane,"Database Error : "+ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //FETCH
        fetch_one_data(jTextField4.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //DELETE
        int ans = JOptionPane.showConfirmDialog(rootPane,"Are you sure to delete ? ");
        if(ans==JOptionPane.YES_OPTION){
            if((oldname.equals(default_img_name) ) ) ///user never gave image in past
            {
                //delete nothing
            }
            else //user already given image in past
            {
                //delete old image 
                File oldimage=new File("user_image\\" + oldname);
                oldimage.delete();
            }
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=null;
            conn=DriverManager.getConnection("jdbc:mysql://localhost/javaproject","root","");
            try{

                String qry = "delete from managestudent where username= ?";
                PreparedStatement st = conn.prepareStatement(qry);
                st.setString(1, jTextField4.getText());

                int rowcount = st.executeUpdate();
                if(rowcount==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"User deleted successfully");
                    clearpage();
                }
                else
                JOptionPane.showMessageDialog(rootPane,"Check all fields");
            }
            catch (Exception ex)
            {
                JOptionPane.showMessageDialog(rootPane,"Query Error : "+ex.getMessage());
            }
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(rootPane,"Database Error : "+ex.getMessage());
        }
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed

    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //update
        if(check_validation()==false)
        return;

    //update image
     String filename="";
     if(myfile==null)
     {
        filename=oldname;
     }
     else //some image is selected
     {
        if(myfile.length()>900000) ///check size of file(image)
        {
            JOptionPane.showMessageDialog(rootPane, "Image is too large");
            File mydfile=new File("user_image//"+oldname);
            try
            {
                Image simg = ImageIO.read( new File(mydfile.getAbsolutePath())).getScaledInstance( jLabel11.getWidth(), jLabel11.getHeight(), Image.SCALE_AREA_AVERAGING);
                jLabel11.setIcon(new ImageIcon(simg));
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, "Cannot read image");
            }
            return;
        }
        else ///new image is selected with correct size 
        {
            filename =new java.util.Date().getTime() + myfile.getName();
            
            int i;
            FileInputStream rd = null;
            FileOutputStream outs = null; 
            try 
            { 
                rd = new FileInputStream(myfile);
                outs = new FileOutputStream("user_image\\"+filename);//writing the new file in 'Images' folder, in the project
                byte[] b = new byte[2048];
                while ((i = rd.read(b)) !=-1) 
                {
                    outs.write(b, 0, i); //copying from pictures to empimages byte by byte 
                } 
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, "error" + e.getMessage());
            }
            finally 
            {
                try 
                {
                    rd.close();
                    outs.close();
                } 
                catch (Exception e) 
                {
                    JOptionPane.showMessageDialog(rootPane, "error in closing file" + e.getMessage());
                }
            }
        } 
        ///delete old image other than default
        if((oldname.equals(default_img_name) ) ) ///user never gave image in past
        {
            //delete nothing
        }
        else //user already given image in past
        {
            //delete old image 
            File oldimage=new File("user_image\\" + oldname);
            oldimage.delete();
        }
 }

        //UPDATE
        try{
           Class.forName("com.mysql.cj.jdbc.Driver");
           Connection conn=null;
           conn=DriverManager.getConnection("jdbc:mysql://localhost/javaproject","root","");
           try{
                String qry = "update managestudent set name = ? ,phone = ? ,gender = ? ,dob = ? ,address = ?"
                + " ,password = ?,branch=?,semester=?,course=? ,pic=? where username= ?"; 
                PreparedStatement st = conn.prepareStatement(qry);
                st.setString(1, jTextField1.getText());
                st.setString(2, jTextField2.getText());
                if(jRadioButton1.isSelected()) 
                    st.setString(3, "male"); 
                else 
                    st.setString(3, "female"); 
                SimpleDateFormat myformat = new SimpleDateFormat("yyyy-MM-dd");
                String d1 = myformat.format( jDateChooser1.getDate() );
                st.setString(4, d1);
                st.setString(5, jTextArea1.getText());
                st.setString(6, jPasswordField1.getText());
                st.setString(7,jComboBox1.getSelectedItem().toString());
                st.setString(8,jComboBox3.getSelectedItem().toString());
                st.setString(9,jComboBox2.getSelectedItem().toString());
                st.setString(10,filename);
                st.setString(11, jTextField4.getText());
                int rowcount = st.executeUpdate();
                if(rowcount==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"User updated successfully");
                    clearpage();
                }
                else
                    
                    JOptionPane.showMessageDialog(rootPane,"Check all fields"); 
                }
                catch (Exception ex) 
                {
                    JOptionPane.showMessageDialog(rootPane,"Query Error : "+ex.getMessage());
                } 
            } 
            catch (Exception ex) 
            {
                JOptionPane.showMessageDialog(rootPane,"Database Error : "+ex.getMessage());
            } 
                                
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        try{    
            if(jComboBox1.getSelectedItem().equals("Btech")){
                jComboBox2.removeAllItems();
                jComboBox2.addItem("CSE");
                jComboBox2.addItem("Civil");
                jComboBox2.addItem("Mechanical");
                jComboBox2.addItem("ECE");
                jComboBox2.setSelectedItem(null);
                
                jComboBox3.removeAllItems();
                jComboBox3.addItem("1");            
                jComboBox3.addItem("2");            
                jComboBox3.addItem("3");            
                jComboBox3.addItem("4");            
                jComboBox3.addItem("5");            
                jComboBox3.addItem("6");            
                jComboBox3.addItem("7");            
                jComboBox3.addItem("8");
            }
            else if(jComboBox1.getSelectedItem().equals("Mtech")){
                jComboBox2.removeAllItems();
                jComboBox2.addItem("CSE");
                jComboBox2.addItem("Civil");
                jComboBox2.addItem("Mechanical");
                jComboBox2.addItem("ECE");  
                jComboBox2.setSelectedItem(null);
                
                jComboBox3.removeAllItems();
                jComboBox3.addItem("1");            
                jComboBox3.addItem("2");            
                jComboBox3.addItem("3");            
                jComboBox3.addItem("4");
            }
            else if(jComboBox1.getSelectedItem().equals("Bsc")){
                jComboBox2.removeAllItems();
                jComboBox2.addItem("Science");
                jComboBox2.addItem("Math");
                jComboBox2.addItem("Physics");   
                jComboBox2.setSelectedItem(null);
                
                jComboBox3.removeAllItems();
                jComboBox3.addItem("1");            
                jComboBox3.addItem("2");            
                jComboBox3.addItem("3");            
                jComboBox3.addItem("4");            
                jComboBox3.addItem("5");            
                jComboBox3.addItem("6");
            }
            else if(jComboBox1.getSelectedItem().equals("Commerce")){
                jComboBox2.removeAllItems();
                jComboBox2.addItem("Bcom");
                jComboBox2.addItem("BBA"); 
                jComboBox2.setSelectedItem(null);
                
                jComboBox3.removeAllItems();
                jComboBox3.addItem("1");            
                jComboBox3.addItem("2");            
                jComboBox3.addItem("3");            
                jComboBox3.addItem("4");            
                jComboBox3.addItem("5");            
                jComboBox3.addItem("6");
            }
        }
        catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, "Error");
            }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        JFileChooser myfilechooser=new JFileChooser(); 
        myfilechooser.setFileFilter(new FileFilter() 
        {
        @Override
        public boolean accept(File f) 
        {
        if(f.isDirectory())
            return true; 
        
        String extension=f.getName().substring(f.getName().lastIndexOf(".")+1);
        String allowed[]={"jpg","png","gif","jpeg","bmp"};
        for(String a:allowed)
        {
            if(a.equals(extension))
            {
                return true;
            }
            else
            {
                return false;
            }
        }
            return false; 
        } 
        @Override
        public String getDescription() 
        {
            return "All Picture Files"; 
        }
        });

            if(myfilechooser.showOpenDialog(rootPane)==JFileChooser.APPROVE_OPTION)
            {
                myfile=myfilechooser.getSelectedFile();
                try
                {
                    Image simg = ImageIO.read( new File(myfile.getAbsolutePath())).getScaledInstance( jLabel11.getWidth(), jLabel11.getHeight(), Image.SCALE_AREA_AVERAGING);
                    jLabel11.setIcon(new ImageIcon(simg));
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane, "Cannot read image");
                }
            }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c) || (c==KeyEvent.VK_BACK_SPACE|| c==KeyEvent.VK_DELETE || c==KeyEvent.VK_SPACE )))
        evt.consume();
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE|| c==KeyEvent.VK_DELETE)))
        evt.consume();
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jDateChooser1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooser1KeyTyped
      
    }//GEN-LAST:event_jDateChooser1KeyTyped

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       ///Search  
        String mypath = "jdbc:mysql://localhost/javaproject";
        String myuser = "root";
        String mypassword = "";
        //name	phone	gender	dob	address	username	password
        try
        {
            Connection conn = DriverManager.getConnection(mypath, myuser, mypassword);
            try
            {
                String qry = "select * from managestudent where name like ?";

                PreparedStatement st = conn.prepareStatement(qry);
                st.setString(1, jTextField1.getText()+"%");
                ResultSet rst = st.executeQuery();
                DefaultTableModel mymodel = (DefaultTableModel) jTable1.getModel();

                mymodel.setRowCount(0);

                if(rst.next())
                {
                    do
                    {
                        String c1 = rst.getString("name");
                        String c2 = rst.getString("phone");
                        String c3 = rst.getString("gender");
                        String c4 = rst.getString("dob");
                        String c5 = rst.getString("address");
                        String c6 = rst.getString("username");

                        // add data in table
                        Object rowData[] = {c1,c2,c3,c4,c5,c6};

                        mymodel.addRow(rowData);

                    }while(rst.next());
                }
                else
                JOptionPane.showMessageDialog(rootPane,"No record for this username");
            }
            catch (Exception ex)
            {
                JOptionPane.showMessageDialog(rootPane,"Query Error : "+ex.getMessage());
            }
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(rootPane,"Database Error : "+ex.getMessage());
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int r = jTable1.getSelectedRow();
        String un = jTable1.getValueAt(r, 5).toString(); 
        fetch_one_data(un);
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
    void clearpage() {
        jTextField1.setText(null);
        jTextField2.setText(null);
        jDateChooser1.setDate(null);
        jTextField4.setText(null);
        jTextArea1.setText(null);
        jPasswordField1.setText(null);
        buttonGroup1.clearSelection();
        
       try
        {
            Image simg = ImageIO.read( new File("user_image//"+default_img_name)).getScaledInstance( jLabel11.getWidth(), jLabel11.getHeight(), Image.SCALE_AREA_AVERAGING);
            jLabel11.setIcon(new ImageIcon(simg));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Cannot read image");
        }
        myfile=null;
    }
    
   void fetch_one_data(String un)
    {
            String mypath = "jdbc:mysql://localhost/javaproject";
            String myuser = "root";
            String mypassword = "";
        //name	phone	gender	dob	address	username	password	
            try 
            {
                Connection conn = DriverManager.getConnection(mypath, myuser, mypassword); 
                try
                {
                    String qry = "select * from managestudent where username = ?"; 

                    PreparedStatement st = conn.prepareStatement(qry);
                    st.setString(1, un); 
                    ResultSet rst = st.executeQuery(); 
                    clearpage(); 
                    if(rst.next())
                    {
                        String c1 = rst.getString("name");
                        String c2 = rst.getString("phone");
                        String c3 = rst.getString("gender");
                        Date c4 = rst.getDate("dob");
                        String c5 = rst.getString("address");
                        String c6 = rst.getString("username");
                        String c7 = rst.getString("password"); 
                        String c8 = rst.getString("branch");
                        String c9 = rst.getString("semester");
                        String c10 = rst.getString("course"); 
                        String c11 = rst.getString("pic");
                        oldname = c11;
                        
                        try
                        {
                            Image simg = ImageIO.read( new File("user_image//"+c11)).getScaledInstance( jLabel11.getWidth(), jLabel11.getHeight(), Image.SCALE_AREA_AVERAGING);
                            jLabel11.setIcon(new ImageIcon(simg));
                        }
                        catch(Exception e)
                        {
                            JOptionPane.showMessageDialog(rootPane, "Cannot read image");
                        }

                        jTextField1.setText(c1);
                        jTextField2.setText(c2);

                        if(c3.equalsIgnoreCase("male"))
                            jRadioButton1.setSelected(true);
                        else
                            jRadioButton2.setSelected(true);

                   jDateChooser1.setDate(c4);
                   jTextArea1.setText(c5);
                   jTextField4.setText(c6);
                   jPasswordField1.setText(c7); 
                   jComboBox1.setSelectedItem(c8);
                   jComboBox3.setSelectedItem(c9);
                   jComboBox2.setSelectedItem(c10);
                }   
                else 
                    JOptionPane.showMessageDialog(rootPane,"No record for this username"); 
            }
            catch (Exception ex) 
            {
                JOptionPane.showMessageDialog(rootPane,"Query Error : "+ex.getMessage());
            } 
        } 
        catch (Exception ex) 
        {
            JOptionPane.showMessageDialog(rootPane,"Database Error : "+ex.getMessage());
        } 
    }
     
    Boolean check_validation()
        {
        if(jTextField1.getText().length()<2)
        {
            JOptionPane.showMessageDialog(rootPane, "Please enter proper name");
            return false;
        }
        else if(jTextField2.getText().length()<7 || jTextField2.getText().length()>15)
        { 
            JOptionPane.showMessageDialog(rootPane, "Please enter Valid phone");
            return false;
        }
        else if(jRadioButton1.isSelected()==false && jRadioButton2.isSelected()==false)
        {
            JOptionPane.showMessageDialog(rootPane, "Please choose gender");
            return false;
        }
        else if(jComboBox1.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(rootPane, "Please choose user type");
            return false;
        }
         return true;
      }
}